### ISSUE TITLE
Unable to Use Quest Item in the Quest Track

### ISSUE THREAD

**Issue by Aeosora** [Shadow-and-Light/shadow-and-light#115] opened 2024-08-20 19:02 UTC
**Description**

I expect it to use the quest item from the quest tracker.

**Shadow & Light Version**
Version 4.81

**ElvUI Version**
13.74

**Steps to Reproduce**

1. I pick up a quest that has a quest item on the side of the screeen.
2. I'm unable to use the quest item properly on the side of the screen when Shadow and Light is enabled.
3. If I disable Shadow and Light I am able to properly use the quest item.

**Expected Behavior**
Normally I am able to just able to click on the item from the quest tracker.

**Actual Behavior**

**ElvUI + S&L Enabled**
Everytime I attempt to use a Quest Item on the side of the screen this error occurs.

**Additional Information**

**Error Log**
Message: Interface/AddOns/ElvUI_SLE/modules/quests/quests.lua:13: attempt to index field 'tex' (a nil value)
Time: Tue Aug 20 14:58:24 2024
Count: 1
Stack: Interface/AddOns/ElvUI_SLE/modules/quests/quests.lua:13: attempt to index field 'tex' (a nil value)
[string "@Interface/AddOns/ElvUI_SLE/modules/quests/quests.lua"]:13: in function `FULL'
[string "@Interface/AddOns/ElvUI_SLE/modules/quests/quests.lua"]:63: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: frame = ObjectiveTrackerFrame {
 modules = <table> {
 }
 systemInfo = <table> {
 }
 downKeys = <table> {
 }
 breakSnappedFramesOnSave = true
 init = true
 dirtySettings = <table> {
 }
 hasActiveChanges = false
 dirty = true
 bottomModulePadding = 10
 snappedFrames = <table> {
 }
 ignoreFramePositionManager = true
 isRightManagedFrame = true
 layoutParent = UIParentRightManagedFrameContainer {
 }
 savedSystemInfo = <table> {
 }
 systemNameString = "Objective Tracker"
 topPadding = 0
 Selection = Frame {
 }
 align = "right"
 editModeHeight = 700
 settingMap = <table> {
 }
 settingDisplayInfoMap = <table> {
 }
 settingsDialogAnchor = <table> {
 }
 Header = Frame {
 }
 NineSlice = Frame {
 }
 layoutIndex = 50
 headerText = "All Objectives"
 needsSorting = false
 moduleSpacing = 10
 topModulePadding = 38
 hideWhenActionBarIsOverriden = false
 isCollapsed = false
 isManagedFrame = true
 system = 12
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = "attempt to index field 'tex' (a nil value)"
E = <table> {
 mylevel = 70
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "DAMAGER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 InversePoints = <table> {
 }
 mynameRealm = "Bazjea - Wyrmrest Accord"
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 myrole = "DAMAGER"
 UFParent = ElvUFParent {
 }
 InfoColor2 = ""
 myname = "Bazjea"
 ActionBars = <table> {
 }
 screenHeight = 1920
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 1
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 250
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 3840
 versionString = "13.74"
 LSM = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Horde"
 myrace = "Troll"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Troll"
 myclass = "WARRIOR"
 wowdate = "Aug 16 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Wyrmrest Accord"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 LibsMinor = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.400000
 resolution = "3840x2160"
 TBC = false
 AnimElastic = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 toc = 110002
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> 

```

**Comment by Repooc** [comment] 2024-08-25 20:49
duplicate of #112

**Closed by Repooc** 2024-08-25 20:49 UTC
Labels: :bug: Bug
